# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "poc_cd_rn.xcodeproj")
    build_app(workspace: "poc_cd_rn.xcworkspace", scheme: "poc_cd_rn")
    upload_to_testflight(
      itc_provider: "776U3MX6DZ"
    )
  end
end
