name: Deploy android internal

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: npm i

      - name: Configure keystore
        working-directory: ./android
        run: |
          ls
          echo "$KEYSTORE_FILE" > app/poc-cd-rn.keystore.b64
          base64 -d -i app/poc-cd-rn.keystore.b64 > app/poc-cd-rn.keystore
          echo "storeFile=poc-cd-rn.keystore" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Create service account secret file
        working-directory: ./android
        run : |
          echo "$SERVICE_ACCOUNT_SECRET" > service-account-secret.json.b64
          base64 -d -i service-account-secret.json.b64 > service-account-secret.json
        env:
          SERVICE_ACCOUNT_SECRET: ${{ secrets.SERVICE_ACCOUNT_SECRET }}

      - name: Setup fastlane
        working-directory: ./android
        run: bundle install

      - name: Distribute app to internal track
        working-directory: ./android
        run: bundle exec fastlane alpha